//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ vygeneroval soubor zahrnutí.
// Použito D:\Programy\PCBeleganceZdroje\sch\resource\sch.rc
//
#define IDHELP                          9
#define IDHELP3                         11
#define IDR_OWNFONT1                    1500
#define IDSKIP                          1600
#define BITMAP_BUTTON_SCH               2000
#define BITMAP_BUTTON_SYM               2003
#define BITMAP_CIRCLE_1                 2004
#define BITMAP_CIRCLE_2                 2005
#define BITMAP_CIRCLE_3                 2006
#define BITMAP_CIRCLE_4                 2007
#define BITMAP_CIRCLE_6                 2008
#define BITMAP_CIRCLE_8                 2009
#define BITMAP_CIRCLE_9                 2010
#define BITMAP_CIRCLE_C                 2011
#define BITMAP_CIRCLE_F                 2012
#define BITMAP_CIRCLE_FILLED            2013
#define BITMAP_INFO                     2014
#define BITMAP_INTRO15                  2015
#define BITMAP_INTRO15A                 2016
#define BITMAP_INTRO20                  2017
#define BITMAP_INTRO20A                 2018
#define BITMAP_INTRO25                  2019
#define BITMAP_INTRO25A                 2020
#define BITMAP_INTRO30                  2021
#define BITMAP_INTRO30A                 2022
#define BITMAP_LINE1                    2023
#define BITMAP_LINE2                    2024
#define BITMAP_LINE3                    2025
#define BITMAP_LINE4                    2026
#define BITMAP_DIMENSION1               2027
#define BITMAP_DIMENSION2               2028
#define BITMAP_INTRO35                  2029
#define BITMAP_INTRO35A                 2030
#define ICON_SHEET                      2100
#define ICON_SYMBOL                     2101
#define IDI_ICON1                       2102
#define IDC_BUTTON1                     2200
#define IDC_BUTTON2                     2201
#define IDC_BUTTON3                     2202
#define IDC_BUTTON4                     2203
#define IDC_BUTTON5                     2204
#define IDC_CHECK1                      2300
#define IDC_CHECK2                      2301
#define IDC_CHECK3                      2302
#define IDC_CHECK4                      2303
#define IDC_CHECK5                      2304
#define IDC_CHECK6                      2305
#define IDC_CHECK7                      2306
#define IDC_CHECK8                      2307
#define IDC_CHECK9                      2308
#define IDC_COMBO1                      2400
#define IDC_COMBO2                      2401
#define IDC_COMBO3                      2402
#define IDC_COMBO4                      2403
#define IDC_TREE1                       2450
#define IDC_EDIT1                       2500
#define IDC_EDIT2                       2501
#define IDC_EDIT3                       2502
#define IDC_EDIT4                       2503
#define IDC_EDIT5                       2504
#define IDC_EDIT6                       2505
#define IDC_EDIT7                       2506
#define IDC_EDIT8                       2507
#define IDC_EDIT9                       2508
#define IDC_EDIT10                      2509
#define IDC_EDIT11                      2510
#define IDC_EDIT12                      2511
#define IDC_LIST1                       2600
#define IDC_LIST2                       2601
#define IDC_LIST3                       2602
#define IDC_LIST4                       2603
#define IDC_LIST5                       2604
#define IDC_LIST6                       2605
#define IDC_RADIO1                      2700
#define IDC_RADIO2                      2701
#define IDC_RADIO3                      2702
#define IDC_RADIO4                      2703
#define IDC_RADIO5                      2704
#define IDC_RADIO6                      2705
#define IDC_RADIO7                      2706
#define IDC_RADIO8                      2707
#define IDC_RADIO9                      2708
#define IDC_RADIO10                     2709
#define IDC_RADIO11                     2710
#define IDC_RADIO12                     2711
#define IDC_RADIO13                     2712
#define IDC_STATIC1                     2800
#define IDC_STATIC2                     2801
#define IDC_STATIC3                     2802
#define IDC_STATIC4                     2803
#define IDC_STATIC5                     2804
#define IDC_STATIC6                     2805
#define IDC_STATIC7                     2806
#define IDC_STATIC8                     2807
#define IDC_STATIC9                     2808
#define IDC_STATIC10                    2809
#define IDC_STATIC11                    2810
#define IDC_STATIC12                    2811
#define IDC_STATIC13                    2812
#define IDC_STATIC14                    2813
#define IDC_STATIC15                    2814
#define IDC_STATIC16                    2815
#define IDC_STATIC17                    2816
#define IDC_STATIC18                    2817
#define IDC_STATIC20                    2819
#define IDC_STATIC21                    2820
#define IDC_STATIC22                    2821
#define IDC_STATIC23                    2822
#define IDC_STATIC24                    2823
#define IDC_STATIC25                    2824
#define IDC_STATIC26                    2825
#define IDC_STATIC27                    2826
#define IDC_STATIC28                    2827
#define IDC_STATIC                      2880
#define IDD_DIALOG_ABOUT                3000
#define IDD_DIALOG_ADDLABEL             3001
#define IDD_DIALOG_ADDLABELS            3002
#define IDD_DIALOG_ADDPINBUS2           3004
#define IDD_DIALOG_ADDPINS              3005
#define IDD_DIALOG_ADDPINS2A            3007
#define IDD_DIALOG_ADDPINS3             3008
#define IDD_DIALOG_ADDPINS4             3009
#define IDD_DIALOG_ADDPOWERPINS         3010
#define IDD_DIALOG_ADDSYMBOL            3011
#define IDD_DIALOG_ADDSYMBOL2           3012
#define IDD_DIALOG_ANNOTATE             3013
#define IDD_DIALOG_BITMAP_OUTPUT        3014
#define IDD_DIALOG_COLOR                3015
#define IDD_DIALOG_EDITGEOMETRY         3016
#define IDD_DIALOG_GATEPINSWAP          3017
#define IDD_DIALOG_INSTANCEINFO         3018
#define IDD_DIALOG_MESSAGE              3019
#define IDD_DIALOG_MESSAGE2             3020
#define IDD_DIALOG_NRPARTS              3021
#define IDD_DIALOG_NUMBERINC            3022
#define IDD_DIALOG_PDF_OUTPUT           3023
#define IDD_DIALOG_PINBUSREORDER        3024
#define IDD_DIALOG_SELECTCOMP           3026
#define IDD_DIALOG_SHEETSYMBOLINFO      3028
#define IDD_DIALOG_SUBPIN               3029
#define IDD_DIALOG_SUBPINSTRINGS        3030
#define BITMAP_RECT_1                   3031
#define BITMAP_RECT_2                   3032
#define IDD_DIALOG_SYMBOLINFO20         3032
#define IDD_DIALOG_TEXTINPUT            3033
#define IDD_DIALOG_TEXTINPUT2           3034
#define IDD_DIALOG_WIRELABEL            3035
#define IDD_DIALOG_EXPORT_DXF           3036
#define IDD_DIALOG_DXFLAYER             3037
#define IDD_DIALOG_TEXTINPUT3           3038
#define IDD_DIALOG_ADDCOMP              3039
#define IDD_DIALOG_PROPERTY             3041
#define IDD_DIALOG_SHEETINFO            3042
#define IDD_DIALOG_VIEW_SHEET           3043
#define IDD_DIALOG_TEXTINPUT4           3044
#define IDD_DIALOG_VIEW_SYMBOL          3045
#define IDD_DIALOG_GEOM_SEARCH          3047
#define IDD_DIALOG_COMP_SEL             3048
#define IDD_DIALOG_REPLACE              3049
#define IDD_UNITS                       3200
#define ID_ADDARC                       3500
#define ID_ADDBUS                       3501
#define ID_ADDBUSCONNECTION             3502
#define ID_ADDCIRCLE                    3503
#define ID_ADDCIRCLE_1                  3504
#define ID_ADDCIRCLE_2                  3505
#define ID_ADDCIRCLE_3                  3506
#define ID_ADDCIRCLE_4                  3507
#define ID_ADDCIRCLE_6                  3508
#define ID_ADDCIRCLE_8                  3509
#define ID_ADDCIRCLE_9                  3510
#define ID_ADDCIRCLE_C                  3511
#define ID_ADDCIRCLE_F                  3512
#define ID_ADDCIRCLE_FILLED             3513
#define ID_ADDCOMP                      3514
#define ID_ADDGLOBALCONNECTION_I        3515
#define ID_ADDGLOBALCONNECTION_IO       3516
#define ID_ADDGLOBALCONNECTION_O        3517
#define ID_ADDJUNCTION                  3518
#define ID_ADDLINE                      3519
#define ID_ADDNETLABEL                  3520
#define ID_ADDNETLABELS                 3521
#define ID_ADDPIN                       3522
#define ID_ADDPINBUS                    3523
#define ID_ADDPOWERPIN                  3524
#define ID_ADDRECT                      3525
#define ID_ADDRECT2                     3526
#define ID_ADDRECT3                     3527
#define ID_ADDSYMBOL                    3528
#define ID_ADDSYMBOL_PREVIEW            3529
#define ID_ADDSYMBOL_READLIB            3530
#define ID_ADDSYMBOL_READLIB2           3531
#define ID_ADDSYMBOL_SHORTCUT           3532
#define ID_ADDTEXT                      3533
#define ID_ADDTEXTNUM                   3534
#define ID_ADDWIRE                      3535
#define ID_ADDWIRELABEL                 3536
#define ID_CHANGE_COLOR                 3537
#define ID_COPY_CLIP                    3538
#define ID_COPY_OBJECTS                 3539
#define ID_COPY_OBJECTS10               3540
#define ID_COPY_OBJECTS2                3541
#define ID_COPY_OBJECTS3                3542
#define ID_COPY_OBJECTS4                3543
#define ID_COPY_OBJECTS5                3544
#define ID_COPY_OBJECTS6                3545
#define ID_COPY_OBJECTS7                3546
#define ID_COPY_OBJECTS8                3547
#define ID_COPY_OBJECTS9                3548
#define ID_DRAG_OBJECTS                 3549
#define ID_EDITSYMBOLNAME               3550
#define ID_EDITSYMBOLREF                3551
#define ID_EDIT_ANNOTATE                3552
#define ID_EDIT_CHECK                   3553
#define ID_EDIT_CLEAR_REFS              3554
#define ID_EDIT_DELETE                  3555
#define ID_EDIT_DELETE_PINBUSREORDER    3556
#define ID_EDIT_EXPORTTEXT              3557
#define ID_EDIT_GATEPINSWAP             3558
#define ID_EDIT_PARTS_NR                3559
#define ID_EDIT_PARTS_PINS              3560
#define ID_EDIT_PROTECT                 3561
#define ID_EDIT_REDO                    3562
#define ID_EDIT_SEARCH_TEXT             3563
#define ID_EDIT_SYMBOLINFO              3564
#define ID_EDIT_SYMBOLNAMES             3565
#define ID_EDIT_TEXT                    3566
#define ID_EDIT_UNDO                    3567
#define ID_EDIT_UNPROTECT               3568
#define ID_EDIT_WIRE_MODE_EXTENDED      3569
#define ID_EDIT_WIRE_MODE_NORMAL        3570
#define ID_EDIT_ZERORELATIVECURSOR      3571
#define ID_ESCAPE                       3572
#define ID_FILE_DELETE_UNDO             3573
#define ID_FILE_EDIT_SHEET              3574
#define ID_FILE_EDIT_SYMBOL             3575
#define ID_FILE_EXIT                    3576
#define ID_FILE_EXPORT_BITMAPS          3577
#define ID_FILE_EXPORT_PDF              3578
#define ID_FILE_NEW_SHEET               3579
#define ID_FILE_NEW_SHEET2              3580
#define ID_FILE_NEW_SHEETSYMBOL         3581
#define ID_FILE_NEW_SHEETSYMBOL2        3582
#define ID_FILE_NEW_SYMBOL              3583
#define ID_FILE_NEW_SYMBOL2             3584
#define ID_FILE_OPEN                    3585
#define ID_FILE_OPEN2                   3586
#define ID_FILE_PRINT                   3587
#define ID_FILE_PRINT_COLOR             3588
#define ID_FILE_PRINT_DEFAULT           3589
#define ID_FILE_SAVE                    3590
#define ID_FILE_SAVEAS                  3591
#define ID_FILE_SHEETBACK               3592
#define ID_HELP_ABOUT                   3593
#define ID_HELP_CONTENTS                3594
#define ID_HELP_ON_COMMAND              3595
#define ID_HELP_REGISTRATION            3596
#define ID_HELP_TOPICS                  3597
#define ID_INSERT_CLIP                  3598
#define ID_INSTANCEINFO_SELECT          3599
#define ID_MIRRORX_OBJECTS              3600
#define ID_MIRRORY_OBJECTS              3601
#define ID_MOVE_OBJECTS                 3602
#define ID_ROTATE_OBJECTS               3603
#define ID_SELECTGEOM_VIEW              3604
#define ID_SEL_ONLY_ARCS                3605
#define ID_SEL_ONLY_BUSCONN             3606
#define ID_SEL_ONLY_BUSSES              3607
#define ID_SEL_ONLY_CIRCLES             3608
#define ID_SEL_ONLY_GLOBALCONN          3609
#define ID_SEL_ONLY_GLOBALCONN_TEXT     3610
#define ID_SEL_ONLY_INST                3611
#define ID_SEL_ONLY_INST_REF            3612
#define ID_SEL_ONLY_INST_VALUE          3613
#define ID_SEL_ONLY_JUNCTIONS           3614
#define ID_SEL_ONLY_LINES               3615
#define ID_SEL_ONLY_NETLABELS           3616
#define ID_SEL_ONLY_PINBUSSES           3617
#define ID_SEL_ONLY_PINS                3618
#define ID_SEL_ONLY_PINTEXTS            3619
#define ID_SEL_ONLY_POWERPINS           3620
#define ID_SEL_ONLY_RECTS               3621
#define ID_SEL_ONLY_TEXTS               3622
#define ID_SEL_ONLY_WIRES               3623
#define ID_UNSELECT_ALL                 3624
#define ID_UNSEL_ARCS                   3625
#define ID_UNSEL_BUSCONN                3626
#define ID_UNSEL_BUSSES                 3627
#define ID_UNSEL_CIRCLES                3628
#define ID_UNSEL_GLOBALCONN             3629
#define ID_UNSEL_GLOBALCONN_TEXT        3630
#define ID_UNSEL_INST                   3631
#define ID_UNSEL_INST_REF               3632
#define ID_UNSEL_INST_VALUE             3633
#define ID_UNSEL_JUNCTIONS              3634
#define ID_UNSEL_LINES                  3635
#define ID_UNSEL_NETLABELS              3636
#define ID_UNSEL_PINBUSSES              3637
#define ID_UNSEL_PINS                   3638
#define ID_UNSEL_PINTEXTS               3639
#define ID_UNSEL_POWERPINS              3640
#define ID_UNSEL_RECTS                  3641
#define ID_UNSEL_TEXTS                  3642
#define ID_UNSEL_WIRES                  3643
#define ID_VIEW_CHANGECOLORS            3644
#define ID_VIEW_LOADDEFAULTCOLORS       3645
#define ID_VIEW_LOADDEFAULTCOLORS2      3646
#define ID_VIEW_MEMINFO                 3647
#define ID_VIEW_PAN                     3648
#define ID_VIEW_PREVIOUS_VIEW           3649
#define ID_VIEW_REPAINT                 3650
#define ID_VIEW_VIEWFULL                3651
#define ID_VIEW_ZOOMIN                  3652
#define ID_VIEW_ZOOMOUT                 3653
#define ID_EXPORT_DXF                   3654
#define ID_IMPORT_DXF                   3655
#define ID_SELECT_ALL                   3656
#define ID_ROTATE_OBJECTS2              3657
#define ID_SCALE_OBJECTS                3658
#define ID_ALIGN_OBJECTS_LEFT           3659
#define ID_ALIGN_OBJECTS_RIGHT          3660
#define ID_CHANGE_LINE_WIDTH            3661
#define ID_CHANGE_TEXT_HEIGHT           3662
#define ID_ADDBUS2                      3663
#define ID_ADDWIRE2                     3664
#define ID_CHANGE_LINE_STYLE1           3665
#define ID_CHANGE_LINE_STYLE2           3666
#define ID_CHANGE_LINE_STYLE3           3667
#define ID_CHANGE_LINE_STYLE4           3668
#define ID_ADD_DIMENSION                3669
#define ID_ADD_DIMENSION2               3670
#define ID_ADD_ARROW1                   3671
#define ID_ADD_ARROW2                   3672
#define ID_ADD_ARROW3                   3673
#define ID_FILE_SAVEAS_VERSION25        3674
#define ID_ADDCOMPONENT                 3675
#define ID_ADDONEPINNET                 3676
#define ID_FILE_SAVEAS_VERSION30        3677
#define ID_EDIT_PROPERTY                3678
#define ID_EDIT_SHEETINFO               3679
#define ID_EDIT_DISPLAY_INFO            3680
#define ID_VIEW_OPTIONS                 3681
#define ID_EDIT_GOTOXY                  3682
#define ID_EDIT_SWAP_NETLABELS          3683
#define ID_EDIT_SWAP_PINS               3684
#define ID_EDIT_MULTIPLE_INSTANCES      3685
#define ID_FILE_SAVE_WITH_ERRORS        3686
#define ID_EDIT_LAYOUT_ON_REF           3687
#define ID_SELECT_COMPS_BY_LIST         3688
#define ID_EDIT_VARS                    3689
#define ID_CHECK_FOR_UPDATES            3690
#define ID_EDIT_SEARCH_NEXT_TEXT        3691
#define ID_REPLACE_TEXTS                3692
#define ID_ADD_TEXT_OBJECTS_FROM_TEXTFILE 3693
#define SELECTIONS_ARCS                 0x1000
#define SELECTIONS_BUSCONN              0x1001
#define SELECTIONS_BUSSES               0x1002
#define SELECTIONS_CIRCLES              0x1003
#define SELECTIONS_GLOBALCONN           0x1004
#define SELECTIONS_GLOBALCONN_TEXT      0x1005
#define SELECTIONS_INST                 0x1006
#define SELECTIONS_INST_REF             0x1007
#define SELECTIONS_INST_VALUE           0x1008
#define SELECTIONS_JUNCTIONS            0x1009
#define SELECTIONS_LINES                0x100A
#define SELECTIONS_NETLABELS            0x100B
#define SELECTIONS_PINBUSSES            0x100C
#define SELECTIONS_PINS                 0x100D
#define SELECTIONS_PINTEXTS             0x100E
#define SELECTIONS_POWERPINS            0x100F
#define SELECTIONS_RECTS                0x1010
#define SELECTIONS_TEXTS                0x1011
#define SELECTIONS_WIRES                0x1012
#define SELECTIONS_ONEPINNETS           0x1013
#define IDC_COMBOBOXEX1                 5211
#define ID_EDIT_PINBUSREORDER           6000
#define ID_ADD_PINBUSREORDER            6100
#define ID_FILE_USED_FILES              6200
#define ID_SCHEMATIC_CHECK              9100
#define ID_POPUP_COMP_SELECT            10000
#define IDM_WINDOWCHILD                 16000
#define IDC_CHECK12                     20311
#define ID_FILE_RELOADGEOMETRIES        22500
#define ID_FILE_RELOAD_SYMBOLS          22501
#define ID_FILE_EXIT_TO_LIB_SCH         22502
#define ID_FILE_EXIT_TO_LIB_GEOM        22503
#define ID_SHEET_GOTOXY                 22602
#define ID_LAYOUT_OPEN_REF              22700
#define ID_VIEW_CENTER_ON_COMPONENT     22800
#define ID_VIEW_CENTER_ON_COMP_PARTNR   22801
#define ID_GLOBAL_FILE_SAVE             23000
#define ID_SEND_WINDOW_SIZE1            23001
#define ID_SEND_WINDOW_SIZE2            23002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        5009
#define _APS_NEXT_COMMAND_VALUE         5100
#define _APS_NEXT_CONTROL_VALUE         5212
#define _APS_NEXT_SYMED_VALUE           5300
#endif
#endif
