/*
 * PCB elegance (Open source tools for making printed circuit boards)
 *
 * Copyright (C) 2012  Herman Morsink Vollenbroek
 *
 * File: keyswin.h
 *
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
/*******************************************************************************************/


#ifndef _KEYSWIN

#define _KEYSWIN

#define vk_LButton              0x01
#define vk_RButton              0x02
#define vk_Cancel               0x03
#define vk_MButton              0x04
#define vk_Back                 0x08
#define vk_Tab                  0x09
#define vk_Clear                0x0C
#define vk_Return               0x0D
#define vk_Shift                0x10
#define vk_Control              0x11
#define vk_Menu                 0x12
#define vk_Pause                0x13
#define vk_Capital              0x14
#define vk_Escape               0x1B
#define vk_Space                0x20
#define vk_Prior                0x21
#define vk_Next                 0x22
#define vk_End                  0x23
#define vk_Home                 0x24
#define vk_Left                 0x25
#define vk_Up                   0x26
#define vk_Right                0x27
#define vk_Down                 0x28
#define vk_Select               0x29
#define vk_Print                0x2A
#define vk_Execute              0x2B
#define vk_SnapShot             0x2C
#define vk_Insert               0x2D
#define vk_Delete               0x2E
#define vk_Help                 0x2F
#define vk_NumPad0              0x60
#define vk_NumPad1              0x61
#define vk_NumPad2              0x62
#define vk_NumPad3              0x63
#define vk_NumPad4              0x64
#define vk_NumPad5              0x65
#define vk_NumPad6              0x66
#define vk_NumPad7              0x67
#define vk_NumPad8              0x68
#define vk_NumPad9              0x69
#define vk_Multiply             0x6A
#define vk_Add                  0x6B
#define vk_Separator            0x6C
#define vk_Subtract             0x6D
#define vk_Decimal              0x6E
#define vk_Divide               0x6F
#define vk_F1                   0x70
#define vk_F2                   0x71
#define vk_F3                   0x72
#define vk_F4                   0x73
#define vk_F5                   0x74
#define vk_F6                   0x75
#define vk_F7                   0x76
#define vk_F8                   0x77
#define vk_F9                   0x78
#define vk_F10                  0x79
#define vk_F11                  0x7A
#define vk_F12                  0x7B
#define vk_F13                  0x7C
#define vk_F14                  0x7D
#define vk_F15                  0x7E
#define vk_F16                  0x7F
#define vk_NumLock              0x90

#define Key_Ctrl_A              0x0241
#define Key_Ctrl_B              0x0242
#define Key_Ctrl_C              0x0243
#define Key_Ctrl_D              0x0244
#define Key_Ctrl_E              0x0245
#define Key_Ctrl_F              0x0246
#define Key_Ctrl_G              0x0247
#define Key_Ctrl_H              0x0248
#define Key_Ctrl_I              0x0249
#define Key_Ctrl_J              0x024A
#define Key_Ctrl_K              0x024B
#define Key_Ctrl_L              0x024C
#define Key_Ctrl_M              0x024D
#define Key_Ctrl_N              0x024E
#define Key_Ctrl_O              0x024F
#define Key_Ctrl_P              0x0250
#define Key_Ctrl_Q              0x0251
#define Key_Ctrl_R              0x0252
#define Key_Ctrl_S              0x0253
#define Key_Ctrl_T              0x0254
#define Key_Ctrl_U              0x0255
#define Key_Ctrl_V              0x0256
#define Key_Ctrl_W              0x0257
#define Key_Ctrl_X              0x0258
#define Key_Ctrl_Y              0x0259
#define Key_Ctrl_Z              0x025A

#define Key_Alt_A               0x0441
#define Key_Alt_B               0x0442
#define Key_Alt_C               0x0443
#define Key_Alt_D               0x0444
#define Key_Alt_E               0x0445
#define Key_Alt_F               0x0446
#define Key_Alt_G               0x0447
#define Key_Alt_H               0x0448
#define Key_Alt_I               0x0449
#define Key_Alt_J               0x044A
#define Key_Alt_K               0x044B
#define Key_Alt_L               0x044C
#define Key_Alt_M               0x044D
#define Key_Alt_N               0x044E
#define Key_Alt_O               0x044F
#define Key_Alt_P               0x0450
#define Key_Alt_Q               0x0451
#define Key_Alt_R               0x0452
#define Key_Alt_S               0x0453
#define Key_Alt_T               0x0454
#define Key_Alt_U               0x0455
#define Key_Alt_V               0x0456
#define Key_Alt_W               0x0457
#define Key_Alt_X               0x0458
#define Key_Alt_Y               0x0459
#define Key_Alt_Z               0x045A

#define Key_Alt_1               0x0431
#define Key_Alt_2               0x0432
#define Key_Alt_3               0x0433
#define Key_Alt_4               0x0434
#define Key_Alt_5               0x0435
#define Key_Alt_6               0x0436
#define Key_Alt_7               0x0437
#define Key_Alt_8               0x0438
#define Key_Alt_9               0x0439
#define Key_Alt_0               0x0430

#define Key_F1                  0x0870
#define Key_F2                  0x0871
#define Key_F3                  0x0872
#define Key_F4                  0x0873
#define Key_F5                  0x0874
#define Key_F6                  0x0875
#define Key_F7                  0x0876
#define Key_F8                  0x0877
#define Key_F9                  0x0878
#define Key_F10                 0x0879
#define Key_F11                 0x087A
#define Key_F12                 0x087B

#define Key_Shift_F1            0x0170
#define Key_Shift_F2            0x0171
#define Key_Shift_F3            0x0172
#define Key_Shift_F4            0x0173
#define Key_Shift_F5            0x0174
#define Key_Shift_F6            0x0175
#define Key_Shift_F7            0x0176
#define Key_Shift_F8            0x0177
#define Key_Shift_F9            0x0178
#define Key_Shift_F10           0x0179
#define Key_Shift_F11           0x017A
#define Key_Shift_F12           0x017B

#define Key_Ctrl_F1             0x0270
#define Key_Ctrl_F2             0x0271
#define Key_Ctrl_F3             0x0272
#define Key_Ctrl_F4             0x0273
#define Key_Ctrl_F5             0x0274
#define Key_Ctrl_F6             0x0275
#define Key_Ctrl_F7             0x0276
#define Key_Ctrl_F8             0x0277
#define Key_Ctrl_F9             0x0278
#define Key_Ctrl_F10            0x0279
#define Key_Ctrl_F11            0x027A
#define Key_Ctrl_F12            0x027B

#define Key_Alt_F1              0x0470
#define Key_Alt_F2              0x0471
#define Key_Alt_F3              0x0472
/*      Key_Alt_F4              0x0473 */
#define Key_Alt_F5              0x0474
#define Key_Alt_F6              0x0475
#define Key_Alt_F7              0x0476
#define Key_Alt_F8              0x0477
#define Key_Alt_F9              0x0478
#define Key_Alt_F10             0x0479
#define Key_Alt_F11             0x047A
#define Key_Alt_F12             0x047B

#define Key_PgDown              0x0822
#define Key_PgUp                0x0821
#define Key_Home                0x0824
#define Key_End                 0x0823
#define Key_Del                 0x082E
#define Key_Ins                 0x082D
#define Key_Shift_PgDown        0x0122
#define Key_Shift_PgUp          0x0121
#define Key_Shift_Home          0x0124
#define Key_Shift_End           0x0123
#define Key_Shift_Del           0x012E
#define Key_Shift_Ins           0x012D
#define Key_Ctrl_PgDown         0x0222
#define Key_Ctrl_PgUp           0x0221
#define Key_Ctrl_Home           0x0224
#define Key_Ctrl_End            0x0223
#define Key_Ctrl_Del            0x022E
#define Key_Ctrl_Ins            0x022D
#define Key_Alt_PgDown          0x0422
#define Key_Alt_PgUp            0x0421
#define Key_Alt_Home            0x0424
#define Key_Alt_End             0x0423
#define Key_Alt_Del             0x042E
#define Key_Alt_Ins             0x042D

#define Key_Cursor_Right        0x0827
#define Key_Cursor_Left         0x0825
#define Key_Cursor_Up           0x0826
#define Key_Cursor_Down         0x0828
#define Key_Shift_Cursor_Right  0x0127
#define Key_Shift_Cursor_Left   0x0125
#define Key_Shift_Cursor_Up     0x0126
#define Key_Shift_Cursor_Down   0x0128
#define Key_Ctrl_Cursor_Right   0x0227
#define Key_Ctrl_Cursor_Left    0x0225
#define Key_Ctrl_Cursor_Up      0x0226
#define Key_Ctrl_Cursor_Down    0x0228
#define Key_Alt_Cursor_Right    0x0427
#define Key_Alt_Cursor_Left     0x0425
#define Key_Alt_Cursor_Up       0x0426
#define Key_Alt_Cursor_Down     0x0428

#define Key_Esc                 0x081B
#define Key_Alt_Esc             0x041B
#define Key_BackSpace           0x0808
#define Key_Ctrl_BackSpace      0x0208
#define Key_Alt_BackSpace       0x0408
#define Key_Enter               0x080D
#define Key_Ctrl_Enter          0x020D
#define Key_Alt_Enter           0x040D
#define Key_Tab                 0x0809
#define Key_Shift_Tab           0x0109
#define Key_Ctrl_Tab            0x0209
/*      Key_Alt_Tab             0x0409 */





#define Ctrl_A_A                0x01E7
#define Ctrl_A_B                0x02E7
#define Ctrl_A_C                0x03E7
#define Ctrl_A_D                0x04E7
#define Ctrl_A_E                0x05E7
#define Ctrl_A_F                0x06E7
#define Ctrl_A_G                0x07E7
#define Ctrl_A_H                0x08E7
#define Ctrl_A_I                0x09E7
#define Ctrl_A_J                0x0AE7
#define Ctrl_A_K                0x0BE7
#define Ctrl_A_L                0x0CE7
#define Ctrl_A_M                0x0DE7
#define Ctrl_A_N                0x0EE7
#define Ctrl_A_O                0x0FE7
#define Ctrl_A_P                0x10E7
#define Ctrl_A_Q                0x11E7
#define Ctrl_A_R                0x12E7
#define Ctrl_A_S                0x13E7
#define Ctrl_A_T                0x14E7
#define Ctrl_A_U                0x15E7
#define Ctrl_A_V                0x16E7
#define Ctrl_A_W                0x17E7
#define Ctrl_A_X                0x18E7
#define Ctrl_A_Y                0x19E7
#define Ctrl_A_Z                0x1AE7
#define Ctrl_A_0                0x1BE7
#define Ctrl_A_1                0x1CE7
#define Ctrl_A_2                0x1DE7
#define Ctrl_A_3                0x1EE7
#define Ctrl_A_4                0x1FE7
#define Ctrl_A_5                0x20E7
#define Ctrl_A_6                0x21E7
#define Ctrl_A_7                0x22E7
#define Ctrl_A_8                0x23E7
#define Ctrl_A_9                0x24E7

#define Ctrl_B_A                0x01E8
#define Ctrl_B_B                0x02E8
#define Ctrl_B_C                0x03E8
#define Ctrl_B_D                0x04E8
#define Ctrl_B_E                0x05E8
#define Ctrl_B_F                0x06E8
#define Ctrl_B_G                0x07E8
#define Ctrl_B_H                0x08E8
#define Ctrl_B_I                0x09E8
#define Ctrl_B_J                0x0AE8
#define Ctrl_B_K                0x0BE8
#define Ctrl_B_L                0x0CE8
#define Ctrl_B_M                0x0DE8
#define Ctrl_B_N                0x0EE8
#define Ctrl_B_O                0x0FE8
#define Ctrl_B_P                0x10E8
#define Ctrl_B_Q                0x11E8
#define Ctrl_B_R                0x12E8
#define Ctrl_B_S                0x13E8
#define Ctrl_B_T                0x14E8
#define Ctrl_B_U                0x15E8
#define Ctrl_B_V                0x16E8
#define Ctrl_B_W                0x17E8
#define Ctrl_B_X                0x18E8
#define Ctrl_B_Y                0x19E8
#define Ctrl_B_Z                0x1AE8
#define Ctrl_B_0                0x1BE8
#define Ctrl_B_1                0x1CE8
#define Ctrl_B_2                0x1DE8
#define Ctrl_B_3                0x1EE8
#define Ctrl_B_4                0x1FE8
#define Ctrl_B_5                0x20E8
#define Ctrl_B_6                0x21E8
#define Ctrl_B_7                0x22E8
#define Ctrl_B_8                0x23E8
#define Ctrl_B_9                0x24E8

#define Ctrl_C_A                0x01E9
#define Ctrl_C_B                0x02E9
#define Ctrl_C_C                0x03E9
#define Ctrl_C_D                0x04E9
#define Ctrl_C_E                0x05E9
#define Ctrl_C_F                0x06E9
#define Ctrl_C_G                0x07E9
#define Ctrl_C_H                0x08E9
#define Ctrl_C_I                0x09E9
#define Ctrl_C_J                0x0AE9
#define Ctrl_C_K                0x0BE9
#define Ctrl_C_L                0x0CE9
#define Ctrl_C_M                0x0DE9
#define Ctrl_C_N                0x0EE9
#define Ctrl_C_O                0x0FE9
#define Ctrl_C_P                0x10E9
#define Ctrl_C_Q                0x11E9
#define Ctrl_C_R                0x12E9
#define Ctrl_C_S                0x13E9
#define Ctrl_C_T                0x14E9
#define Ctrl_C_U                0x15E9
#define Ctrl_C_V                0x16E9
#define Ctrl_C_W                0x17E9
#define Ctrl_C_X                0x18E9
#define Ctrl_C_Y                0x19E9
#define Ctrl_C_Z                0x1AE9
#define Ctrl_C_0                0x1BE9
#define Ctrl_C_1                0x1CE9
#define Ctrl_C_2                0x1DE9
#define Ctrl_C_3                0x1EE9
#define Ctrl_C_4                0x1FE9
#define Ctrl_C_5                0x20E9
#define Ctrl_C_6                0x21E9
#define Ctrl_C_7                0x22E9
#define Ctrl_C_8                0x23E9
#define Ctrl_C_9                0x24E9

#define Ctrl_D_A                0x01EA
#define Ctrl_D_B                0x02EA
#define Ctrl_D_C                0x03EA
#define Ctrl_D_D                0x04EA
#define Ctrl_D_E                0x05EA
#define Ctrl_D_F                0x06EA
#define Ctrl_D_G                0x07EA
#define Ctrl_D_H                0x08EA
#define Ctrl_D_I                0x09EA
#define Ctrl_D_J                0x0AEA
#define Ctrl_D_K                0x0BEA
#define Ctrl_D_L                0x0CEA
#define Ctrl_D_M                0x0DEA
#define Ctrl_D_N                0x0EEA
#define Ctrl_D_O                0x0FEA
#define Ctrl_D_P                0x10EA
#define Ctrl_D_Q                0x11EA
#define Ctrl_D_R                0x12EA
#define Ctrl_D_S                0x13EA
#define Ctrl_D_T                0x14EA
#define Ctrl_D_U                0x15EA
#define Ctrl_D_V                0x16EA
#define Ctrl_D_W                0x17EA
#define Ctrl_D_X                0x18EA
#define Ctrl_D_Y                0x19EA
#define Ctrl_D_Z                0x1AEA
#define Ctrl_D_0                0x1BEA
#define Ctrl_D_1                0x1CEA
#define Ctrl_D_2                0x1DEA
#define Ctrl_D_3                0x1EEA
#define Ctrl_D_4                0x1FEA
#define Ctrl_D_5                0x20EA
#define Ctrl_D_6                0x21EA
#define Ctrl_D_7                0x22EA
#define Ctrl_D_8                0x23EA
#define Ctrl_D_9                0x24EA


#define Ctrl_E_A                0x01EB
#define Ctrl_E_B                0x02EB
#define Ctrl_E_C                0x03EB
#define Ctrl_E_D                0x04EB
#define Ctrl_E_E                0x05EB
#define Ctrl_E_F                0x06EB
#define Ctrl_E_G                0x07EB
#define Ctrl_E_H                0x08EB
#define Ctrl_E_I                0x09EB
#define Ctrl_E_J                0x0AEB
#define Ctrl_E_K                0x0BEB
#define Ctrl_E_L                0x0CEB
#define Ctrl_E_M                0x0DEB
#define Ctrl_E_N                0x0EEB
#define Ctrl_E_O                0x0FEB
#define Ctrl_E_P                0x10EB
#define Ctrl_E_Q                0x11EB
#define Ctrl_E_R                0x12EB
#define Ctrl_E_S                0x13EB
#define Ctrl_E_T                0x14EB
#define Ctrl_E_U                0x15EB
#define Ctrl_E_V                0x16EB
#define Ctrl_E_W                0x17EB
#define Ctrl_E_X                0x18EB
#define Ctrl_E_Y                0x19EB
#define Ctrl_E_Z                0x1AEB
#define Ctrl_E_0                0x1BEB
#define Ctrl_E_1                0x1CEB
#define Ctrl_E_2                0x1DEB
#define Ctrl_E_3                0x1EEB
#define Ctrl_E_4                0x1FEB
#define Ctrl_E_5                0x20EB
#define Ctrl_E_6                0x21EB
#define Ctrl_E_7                0x22EB
#define Ctrl_E_8                0x23EB
#define Ctrl_E_9                0x24EB

#define Ctrl_F_A                0x01EC
#define Ctrl_F_B                0x02EC
#define Ctrl_F_C                0x03EC
#define Ctrl_F_D                0x04EC
#define Ctrl_F_E                0x05EC
#define Ctrl_F_F                0x06EC
#define Ctrl_F_G                0x07EC
#define Ctrl_F_H                0x08EC
#define Ctrl_F_I                0x09EC
#define Ctrl_F_J                0x0AEC
#define Ctrl_F_K                0x0BEC
#define Ctrl_F_L                0x0CEC
#define Ctrl_F_M                0x0DEC
#define Ctrl_F_N                0x0EEC
#define Ctrl_F_O                0x0FEC
#define Ctrl_F_P                0x10EC
#define Ctrl_F_Q                0x11EC
#define Ctrl_F_R                0x12EC
#define Ctrl_F_S                0x13EC
#define Ctrl_F_T                0x14EC
#define Ctrl_F_U                0x15EC
#define Ctrl_F_V                0x16EC
#define Ctrl_F_W                0x17EC
#define Ctrl_F_X                0x18EC
#define Ctrl_F_Y                0x19EC
#define Ctrl_F_Z                0x1AEC
#define Ctrl_F_0                0x1BEC
#define Ctrl_F_1                0x1CEC
#define Ctrl_F_2                0x1DEC
#define Ctrl_F_3                0x1EEC
#define Ctrl_F_4                0x1FEC
#define Ctrl_F_5                0x20EC
#define Ctrl_F_6                0x21EC
#define Ctrl_F_7                0x22EC
#define Ctrl_F_8                0x23EC
#define Ctrl_F_9                0x24EC

#define Ctrl_G_A                0x01ED
#define Ctrl_G_B                0x02ED
#define Ctrl_G_C                0x03ED
#define Ctrl_G_D                0x04ED
#define Ctrl_G_E                0x05ED
#define Ctrl_G_F                0x06ED
#define Ctrl_G_G                0x07ED
#define Ctrl_G_H                0x08ED
#define Ctrl_G_I                0x09ED
#define Ctrl_G_J                0x0AED
#define Ctrl_G_K                0x0BED
#define Ctrl_G_L                0x0CED
#define Ctrl_G_M                0x0DED
#define Ctrl_G_N                0x0EED
#define Ctrl_G_O                0x0FED
#define Ctrl_G_P                0x10ED
#define Ctrl_G_Q                0x11ED
#define Ctrl_G_R                0x12ED
#define Ctrl_G_S                0x13ED
#define Ctrl_G_T                0x14ED
#define Ctrl_G_U                0x15ED
#define Ctrl_G_V                0x16ED
#define Ctrl_G_W                0x17ED
#define Ctrl_G_X                0x18ED
#define Ctrl_G_Y                0x19ED
#define Ctrl_G_Z                0x1AED
#define Ctrl_G_0                0x1BED
#define Ctrl_G_1                0x1CED
#define Ctrl_G_2                0x1DED
#define Ctrl_G_3                0x1EED
#define Ctrl_G_4                0x1FED
#define Ctrl_G_5                0x20ED
#define Ctrl_G_6                0x21ED
#define Ctrl_G_7                0x22ED
#define Ctrl_G_8                0x23ED
#define Ctrl_G_9                0x24ED

#define Ctrl_H_A                0x01EE
#define Ctrl_H_B                0x02EE
#define Ctrl_H_C                0x03EE
#define Ctrl_H_D                0x04EE
#define Ctrl_H_E                0x05EE
#define Ctrl_H_F                0x06EE
#define Ctrl_H_G                0x07EE
#define Ctrl_H_H                0x08EE
#define Ctrl_H_I                0x09EE
#define Ctrl_H_J                0x0AEE
#define Ctrl_H_K                0x0BEE
#define Ctrl_H_L                0x0CEE
#define Ctrl_H_M                0x0DEE
#define Ctrl_H_N                0x0EEE
#define Ctrl_H_O                0x0FEE
#define Ctrl_H_P                0x10EE
#define Ctrl_H_Q                0x11EE
#define Ctrl_H_R                0x12EE
#define Ctrl_H_S                0x13EE
#define Ctrl_H_T                0x14EE
#define Ctrl_H_U                0x15EE
#define Ctrl_H_V                0x16EE
#define Ctrl_H_W                0x17EE
#define Ctrl_H_X                0x18EE
#define Ctrl_H_Y                0x19EE
#define Ctrl_H_Z                0x1AEE
#define Ctrl_H_0                0x1BEE
#define Ctrl_H_1                0x1CEE
#define Ctrl_H_2                0x1DEE
#define Ctrl_H_3                0x1EEE
#define Ctrl_H_4                0x1FEE
#define Ctrl_H_5                0x20EE
#define Ctrl_H_6                0x21EE
#define Ctrl_H_7                0x22EE
#define Ctrl_H_8                0x23EE
#define Ctrl_H_9                0x24EE


#define Ctrl_I_A                0x01EF
#define Ctrl_I_B                0x02EF
#define Ctrl_I_C                0x03EF
#define Ctrl_I_D                0x04EF
#define Ctrl_I_E                0x05EF
#define Ctrl_I_F                0x06EF
#define Ctrl_I_G                0x07EF
#define Ctrl_I_H                0x08EF
#define Ctrl_I_I                0x09EF
#define Ctrl_I_J                0x0AEF
#define Ctrl_I_K                0x0BEF
#define Ctrl_I_L                0x0CEF
#define Ctrl_I_M                0x0DEF
#define Ctrl_I_N                0x0EEF
#define Ctrl_I_O                0x0FEF
#define Ctrl_I_P                0x10EF
#define Ctrl_I_Q                0x11EF
#define Ctrl_I_R                0x12EF
#define Ctrl_I_S                0x13EF
#define Ctrl_I_T                0x14EF
#define Ctrl_I_U                0x15EF
#define Ctrl_I_V                0x16EF
#define Ctrl_I_W                0x17EF
#define Ctrl_I_X                0x18EF
#define Ctrl_I_Y                0x19EF
#define Ctrl_I_Z                0x1AEF
#define Ctrl_I_0                0x1BEF
#define Ctrl_I_1                0x1CEF
#define Ctrl_I_2                0x1DEF
#define Ctrl_I_3                0x1EEF
#define Ctrl_I_4                0x1FEF
#define Ctrl_I_5                0x20EF
#define Ctrl_I_6                0x21EF
#define Ctrl_I_7                0x22EF
#define Ctrl_I_8                0x23EF
#define Ctrl_I_9                0x24EF

#define Ctrl_J_A                0x01F0
#define Ctrl_J_B                0x02F0
#define Ctrl_J_C                0x03F0
#define Ctrl_J_D                0x04F0
#define Ctrl_J_E                0x05F0
#define Ctrl_J_F                0x06F0
#define Ctrl_J_G                0x07F0
#define Ctrl_J_H                0x08F0
#define Ctrl_J_I                0x09F0
#define Ctrl_J_J                0x0AF0
#define Ctrl_J_K                0x0BF0
#define Ctrl_J_L                0x0CF0
#define Ctrl_J_M                0x0DF0
#define Ctrl_J_N                0x0EF0
#define Ctrl_J_O                0x0FF0
#define Ctrl_J_P                0x10F0
#define Ctrl_J_Q                0x11F0
#define Ctrl_J_R                0x12F0
#define Ctrl_J_S                0x13F0
#define Ctrl_J_T                0x14F0
#define Ctrl_J_U                0x15F0
#define Ctrl_J_V                0x16F0
#define Ctrl_J_W                0x17F0
#define Ctrl_J_X                0x18F0
#define Ctrl_J_Y                0x19F0
#define Ctrl_J_Z                0x1AF0
#define Ctrl_J_0                0x1BF0
#define Ctrl_J_1                0x1CF0
#define Ctrl_J_2                0x1DF0
#define Ctrl_J_3                0x1EF0
#define Ctrl_J_4                0x1FF0
#define Ctrl_J_5                0x20F0
#define Ctrl_J_6                0x21F0
#define Ctrl_J_7                0x22F0
#define Ctrl_J_8                0x23F0
#define Ctrl_J_9                0x24F0

#define Ctrl_K_A                0x01F1
#define Ctrl_K_B                0x02F1
#define Ctrl_K_C                0x03F1
#define Ctrl_K_D                0x04F1
#define Ctrl_K_E                0x05F1
#define Ctrl_K_F                0x06F1
#define Ctrl_K_G                0x07F1
#define Ctrl_K_H                0x08F1
#define Ctrl_K_I                0x09F1
#define Ctrl_K_J                0x0AF1
#define Ctrl_K_K                0x0BF1
#define Ctrl_K_L                0x0CF1
#define Ctrl_K_M                0x0DF1
#define Ctrl_K_N                0x0EF1
#define Ctrl_K_O                0x0FF1
#define Ctrl_K_P                0x10F1
#define Ctrl_K_Q                0x11F1
#define Ctrl_K_R                0x12F1
#define Ctrl_K_S                0x13F1
#define Ctrl_K_T                0x14F1
#define Ctrl_K_U                0x15F1
#define Ctrl_K_V                0x16F1
#define Ctrl_K_W                0x17F1
#define Ctrl_K_X                0x18F1
#define Ctrl_K_Y                0x19F1
#define Ctrl_K_Z                0x1AF1
#define Ctrl_K_0                0x1BF1
#define Ctrl_K_1                0x1CF1
#define Ctrl_K_2                0x1DF1
#define Ctrl_K_3                0x1EF1
#define Ctrl_K_4                0x1FF1
#define Ctrl_K_5                0x20F1
#define Ctrl_K_6                0x21F1
#define Ctrl_K_7                0x22F1
#define Ctrl_K_8                0x23F1
#define Ctrl_K_9                0x24F1

#define Ctrl_L_A                0x01F2
#define Ctrl_L_B                0x02F2
#define Ctrl_L_C                0x03F2
#define Ctrl_L_D                0x04F2
#define Ctrl_L_E                0x05F2
#define Ctrl_L_F                0x06F2
#define Ctrl_L_G                0x07F2
#define Ctrl_L_H                0x08F2
#define Ctrl_L_I                0x09F2
#define Ctrl_L_J                0x0AF2
#define Ctrl_L_K                0x0BF2
#define Ctrl_L_L                0x0CF2
#define Ctrl_L_M                0x0DF2
#define Ctrl_L_N                0x0EF2
#define Ctrl_L_O                0x0FF2
#define Ctrl_L_P                0x10F2
#define Ctrl_L_Q                0x11F2
#define Ctrl_L_R                0x12F2
#define Ctrl_L_S                0x13F2
#define Ctrl_L_T                0x14F2
#define Ctrl_L_U                0x15F2
#define Ctrl_L_V                0x16F2
#define Ctrl_L_W                0x17F2
#define Ctrl_L_X                0x18F2
#define Ctrl_L_Y                0x19F2
#define Ctrl_L_Z                0x1AF2
#define Ctrl_L_0                0x1BF2
#define Ctrl_L_1                0x1CF2
#define Ctrl_L_2                0x1DF2
#define Ctrl_L_3                0x1EF2
#define Ctrl_L_4                0x1FF2
#define Ctrl_L_5                0x20F2
#define Ctrl_L_6                0x21F2
#define Ctrl_L_7                0x22F2
#define Ctrl_L_8                0x23F2
#define Ctrl_L_9                0x24F2

#define Ctrl_M_A                0x01F3
#define Ctrl_M_B                0x02F3
#define Ctrl_M_C                0x03F3
#define Ctrl_M_D                0x04F3
#define Ctrl_M_E                0x05F3
#define Ctrl_M_F                0x06F3
#define Ctrl_M_G                0x07F3
#define Ctrl_M_H                0x08F3
#define Ctrl_M_I                0x09F3
#define Ctrl_M_J                0x0AF3
#define Ctrl_M_K                0x0BF3
#define Ctrl_M_L                0x0CF3
#define Ctrl_M_M                0x0DF3
#define Ctrl_M_N                0x0EF3
#define Ctrl_M_O                0x0FF3
#define Ctrl_M_P                0x10F3
#define Ctrl_M_Q                0x11F3
#define Ctrl_M_R                0x12F3
#define Ctrl_M_S                0x13F3
#define Ctrl_M_T                0x14F3
#define Ctrl_M_U                0x15F3
#define Ctrl_M_V                0x16F3
#define Ctrl_M_W                0x17F3
#define Ctrl_M_X                0x18F3
#define Ctrl_M_Y                0x19F3
#define Ctrl_M_Z                0x1AF3
#define Ctrl_M_0                0x1BF3
#define Ctrl_M_1                0x1CF3
#define Ctrl_M_2                0x1DF3
#define Ctrl_M_3                0x1EF3
#define Ctrl_M_4                0x1FF3
#define Ctrl_M_5                0x20F3
#define Ctrl_M_6                0x21F3
#define Ctrl_M_7                0x22F3
#define Ctrl_M_8                0x23F3
#define Ctrl_M_9                0x24F3

#define Ctrl_N_A                0x01F4
#define Ctrl_N_B                0x02F4
#define Ctrl_N_C                0x03F4
#define Ctrl_N_D                0x04F4
#define Ctrl_N_E                0x05F4
#define Ctrl_N_F                0x06F4
#define Ctrl_N_G                0x07F4
#define Ctrl_N_H                0x08F4
#define Ctrl_N_I                0x09F4
#define Ctrl_N_J                0x0AF4
#define Ctrl_N_K                0x0BF4
#define Ctrl_N_L                0x0CF4
#define Ctrl_N_M                0x0DF4
#define Ctrl_N_N                0x0EF4
#define Ctrl_N_O                0x0FF4
#define Ctrl_N_P                0x10F4
#define Ctrl_N_Q                0x11F4
#define Ctrl_N_R                0x12F4
#define Ctrl_N_S                0x13F4
#define Ctrl_N_T                0x14F4
#define Ctrl_N_U                0x15F4
#define Ctrl_N_V                0x16F4
#define Ctrl_N_W                0x17F4
#define Ctrl_N_X                0x18F4
#define Ctrl_N_Y                0x19F4
#define Ctrl_N_Z                0x1AF4
#define Ctrl_N_0                0x1BF4
#define Ctrl_N_1                0x1CF4
#define Ctrl_N_2                0x1DF4
#define Ctrl_N_3                0x1EF4
#define Ctrl_N_4                0x1FF4
#define Ctrl_N_5                0x20F4
#define Ctrl_N_6                0x21F4
#define Ctrl_N_7                0x22F4
#define Ctrl_N_8                0x23F4
#define Ctrl_N_9                0x24F4

#define Ctrl_O_A                0x01F5
#define Ctrl_O_B                0x02F5
#define Ctrl_O_C                0x03F5
#define Ctrl_O_D                0x04F5
#define Ctrl_O_E                0x05F5
#define Ctrl_O_F                0x06F5
#define Ctrl_O_G                0x07F5
#define Ctrl_O_H                0x08F5
#define Ctrl_O_I                0x09F5
#define Ctrl_O_J                0x0AF5
#define Ctrl_O_K                0x0BF5
#define Ctrl_O_L                0x0CF5
#define Ctrl_O_M                0x0DF5
#define Ctrl_O_N                0x0EF5
#define Ctrl_O_O                0x0FF5
#define Ctrl_O_P                0x10F5
#define Ctrl_O_Q                0x11F5
#define Ctrl_O_R                0x12F5
#define Ctrl_O_S                0x13F5
#define Ctrl_O_T                0x14F5
#define Ctrl_O_U                0x15F5
#define Ctrl_O_V                0x16F5
#define Ctrl_O_W                0x17F5
#define Ctrl_O_X                0x18F5
#define Ctrl_O_Y                0x19F5
#define Ctrl_O_Z                0x1AF5
#define Ctrl_O_0                0x1BF5
#define Ctrl_O_1                0x1CF5
#define Ctrl_O_2                0x1DF5
#define Ctrl_O_3                0x1EF5
#define Ctrl_O_4                0x1FF5
#define Ctrl_O_5                0x20F5
#define Ctrl_O_6                0x21F5
#define Ctrl_O_7                0x22F5
#define Ctrl_O_8                0x23F5
#define Ctrl_O_9                0x24F5

#define Ctrl_P_A                0x01F6
#define Ctrl_P_B                0x02F6
#define Ctrl_P_C                0x03F6
#define Ctrl_P_D                0x04F6
#define Ctrl_P_E                0x05F6
#define Ctrl_P_F                0x06F6
#define Ctrl_P_G                0x07F6
#define Ctrl_P_H                0x08F6
#define Ctrl_P_I                0x09F6
#define Ctrl_P_J                0x0AF6
#define Ctrl_P_K                0x0BF6
#define Ctrl_P_L                0x0CF6
#define Ctrl_P_M                0x0DF6
#define Ctrl_P_N                0x0EF6
#define Ctrl_P_O                0x0FF6
#define Ctrl_P_P                0x10F6
#define Ctrl_P_Q                0x11F6
#define Ctrl_P_R                0x12F6
#define Ctrl_P_S                0x13F6
#define Ctrl_P_T                0x14F6
#define Ctrl_P_U                0x15F6
#define Ctrl_P_V                0x16F6
#define Ctrl_P_W                0x17F6
#define Ctrl_P_X                0x18F6
#define Ctrl_P_Y                0x19F6
#define Ctrl_P_Z                0x1AF6
#define Ctrl_P_0                0x1BF6
#define Ctrl_P_1                0x1CF6
#define Ctrl_P_2                0x1DF6
#define Ctrl_P_3                0x1EF6
#define Ctrl_P_4                0x1FF6
#define Ctrl_P_5                0x20F6
#define Ctrl_P_6                0x21F6
#define Ctrl_P_7                0x22F6
#define Ctrl_P_8                0x23F6
#define Ctrl_P_9                0x24F6

#define Ctrl_Q_A                0x01F7
#define Ctrl_Q_B                0x02F7
#define Ctrl_Q_C                0x03F7
#define Ctrl_Q_D                0x04F7
#define Ctrl_Q_E                0x05F7
#define Ctrl_Q_F                0x06F7
#define Ctrl_Q_G                0x07F7
#define Ctrl_Q_H                0x08F7
#define Ctrl_Q_I                0x09F7
#define Ctrl_Q_J                0x0AF7
#define Ctrl_Q_K                0x0BF7
#define Ctrl_Q_L                0x0CF7
#define Ctrl_Q_M                0x0DF7
#define Ctrl_Q_N                0x0EF7
#define Ctrl_Q_O                0x0FF7
#define Ctrl_Q_P                0x10F7
#define Ctrl_Q_Q                0x11F7
#define Ctrl_Q_R                0x12F7
#define Ctrl_Q_S                0x13F7
#define Ctrl_Q_T                0x14F7
#define Ctrl_Q_U                0x15F7
#define Ctrl_Q_V                0x16F7
#define Ctrl_Q_W                0x17F7
#define Ctrl_Q_X                0x18F7
#define Ctrl_Q_Y                0x19F7
#define Ctrl_Q_Z                0x1AF7
#define Ctrl_Q_0                0x1BF7
#define Ctrl_Q_1                0x1CF7
#define Ctrl_Q_2                0x1DF7
#define Ctrl_Q_3                0x1EF7
#define Ctrl_Q_4                0x1FF7
#define Ctrl_Q_5                0x20F7
#define Ctrl_Q_6                0x21F7
#define Ctrl_Q_7                0x22F7
#define Ctrl_Q_8                0x23F7
#define Ctrl_Q_9                0x24F7


#define Ctrl_R_A                0x01F8
#define Ctrl_R_B                0x02F8
#define Ctrl_R_C                0x03F8
#define Ctrl_R_D                0x04F8
#define Ctrl_R_E                0x05F8
#define Ctrl_R_F                0x06F8
#define Ctrl_R_G                0x07F8
#define Ctrl_R_H                0x08F8
#define Ctrl_R_I                0x09F8
#define Ctrl_R_J                0x0AF8
#define Ctrl_R_K                0x0BF8
#define Ctrl_R_L                0x0CF8
#define Ctrl_R_M                0x0DF8
#define Ctrl_R_N                0x0EF8
#define Ctrl_R_O                0x0FF8
#define Ctrl_R_P                0x10F8
#define Ctrl_R_Q                0x11F8
#define Ctrl_R_R                0x12F8
#define Ctrl_R_S                0x13F8
#define Ctrl_R_T                0x14F8
#define Ctrl_R_U                0x15F8
#define Ctrl_R_V                0x16F8
#define Ctrl_R_W                0x17F8
#define Ctrl_R_X                0x18F8
#define Ctrl_R_Y                0x19F8
#define Ctrl_R_Z                0x1AF8
#define Ctrl_R_0                0x1BF8
#define Ctrl_R_1                0x1CF8
#define Ctrl_R_2                0x1DF8
#define Ctrl_R_3                0x1EF8
#define Ctrl_R_4                0x1FF8
#define Ctrl_R_5                0x20F8
#define Ctrl_R_6                0x21F8
#define Ctrl_R_7                0x22F8
#define Ctrl_R_8                0x23F8
#define Ctrl_R_9                0x24F8

#define Ctrl_S_A                0x01F9
#define Ctrl_S_B                0x02F9
#define Ctrl_S_C                0x03F9
#define Ctrl_S_D                0x04F9
#define Ctrl_S_E                0x05F9
#define Ctrl_S_F                0x06F9
#define Ctrl_S_G                0x07F9
#define Ctrl_S_H                0x08F9
#define Ctrl_S_I                0x09F9
#define Ctrl_S_J                0x0AF9
#define Ctrl_S_K                0x0BF9
#define Ctrl_S_L                0x0CF9
#define Ctrl_S_M                0x0DF9
#define Ctrl_S_N                0x0EF9
#define Ctrl_S_O                0x0FF9
#define Ctrl_S_P                0x10F9
#define Ctrl_S_Q                0x11F9
#define Ctrl_S_R                0x12F9
#define Ctrl_S_S                0x13F9
#define Ctrl_S_T                0x14F9
#define Ctrl_S_U                0x15F9
#define Ctrl_S_V                0x16F9
#define Ctrl_S_W                0x17F9
#define Ctrl_S_X                0x18F9
#define Ctrl_S_Y                0x19F9
#define Ctrl_S_Z                0x1AF9
#define Ctrl_S_0                0x1BF9
#define Ctrl_S_1                0x1CF9
#define Ctrl_S_2                0x1DF9
#define Ctrl_S_3                0x1EF9
#define Ctrl_S_4                0x1FF9
#define Ctrl_S_5                0x20F9
#define Ctrl_S_6                0x21F9
#define Ctrl_S_7                0x22F9
#define Ctrl_S_8                0x23F9
#define Ctrl_S_9                0x24F9

#define Ctrl_T_A                0x01FA
#define Ctrl_T_B                0x02FA
#define Ctrl_T_C                0x03FA
#define Ctrl_T_D                0x04FA
#define Ctrl_T_E                0x05FA
#define Ctrl_T_F                0x06FA
#define Ctrl_T_G                0x07FA
#define Ctrl_T_H                0x08FA
#define Ctrl_T_I                0x09FA
#define Ctrl_T_J                0x0AFA
#define Ctrl_T_K                0x0BFA
#define Ctrl_T_L                0x0CFA
#define Ctrl_T_M                0x0DFA
#define Ctrl_T_N                0x0EFA
#define Ctrl_T_O                0x0FFA
#define Ctrl_T_P                0x10FA
#define Ctrl_T_Q                0x11FA
#define Ctrl_T_R                0x12FA
#define Ctrl_T_S                0x13FA
#define Ctrl_T_T                0x14FA
#define Ctrl_T_U                0x15FA
#define Ctrl_T_V                0x16FA
#define Ctrl_T_W                0x17FA
#define Ctrl_T_X                0x18FA
#define Ctrl_T_Y                0x19FA
#define Ctrl_T_Z                0x1AFA
#define Ctrl_T_0                0x1BFA
#define Ctrl_T_1                0x1CFA
#define Ctrl_T_2                0x1DFA
#define Ctrl_T_3                0x1EFA
#define Ctrl_T_4                0x1FFA
#define Ctrl_T_5                0x20FA
#define Ctrl_T_6                0x21FA
#define Ctrl_T_7                0x22FA
#define Ctrl_T_8                0x23FA
#define Ctrl_T_9                0x24FA

#define Ctrl_U_A                0x01FB
#define Ctrl_U_B                0x02FB
#define Ctrl_U_C                0x03FB
#define Ctrl_U_D                0x04FB
#define Ctrl_U_E                0x05FB
#define Ctrl_U_F                0x06FB
#define Ctrl_U_G                0x07FB
#define Ctrl_U_H                0x08FB
#define Ctrl_U_I                0x09FB
#define Ctrl_U_J                0x0AFB
#define Ctrl_U_K                0x0BFB
#define Ctrl_U_L                0x0CFB
#define Ctrl_U_M                0x0DFB
#define Ctrl_U_N                0x0EFB
#define Ctrl_U_O                0x0FFB
#define Ctrl_U_P                0x10FB
#define Ctrl_U_Q                0x11FB
#define Ctrl_U_R                0x12FB
#define Ctrl_U_S                0x13FB
#define Ctrl_U_T                0x14FB
#define Ctrl_U_U                0x15FB
#define Ctrl_U_V                0x16FB
#define Ctrl_U_W                0x17FB
#define Ctrl_U_X                0x18FB
#define Ctrl_U_Y                0x19FB
#define Ctrl_U_Z                0x1AFB
#define Ctrl_U_0                0x1BFB
#define Ctrl_U_1                0x1CFB
#define Ctrl_U_2                0x1DFB
#define Ctrl_U_3                0x1EFB
#define Ctrl_U_4                0x1FFB
#define Ctrl_U_5                0x20FB
#define Ctrl_U_6                0x21FB
#define Ctrl_U_7                0x22FB
#define Ctrl_U_8                0x23FB
#define Ctrl_U_9                0x24FB

#define Ctrl_V_A                0x01FC
#define Ctrl_V_B                0x02FC
#define Ctrl_V_C                0x03FC
#define Ctrl_V_D                0x04FC
#define Ctrl_V_E                0x05FC
#define Ctrl_V_F                0x06FC
#define Ctrl_V_G                0x07FC
#define Ctrl_V_H                0x08FC
#define Ctrl_V_I                0x09FC
#define Ctrl_V_J                0x0AFC
#define Ctrl_V_K                0x0BFC
#define Ctrl_V_L                0x0CFC
#define Ctrl_V_M                0x0DFC
#define Ctrl_V_N                0x0EFC
#define Ctrl_V_O                0x0FFC
#define Ctrl_V_P                0x10FC
#define Ctrl_V_Q                0x11FC
#define Ctrl_V_R                0x12FC
#define Ctrl_V_S                0x13FC
#define Ctrl_V_T                0x14FC
#define Ctrl_V_U                0x15FC
#define Ctrl_V_V                0x16FC
#define Ctrl_V_W                0x17FC
#define Ctrl_V_X                0x18FC
#define Ctrl_V_Y                0x19FC
#define Ctrl_V_Z                0x1AFC
#define Ctrl_V_0                0x1BFC
#define Ctrl_V_1                0x1CFC
#define Ctrl_V_2                0x1DFC
#define Ctrl_V_3                0x1EFC
#define Ctrl_V_4                0x1FFC
#define Ctrl_V_5                0x20FC
#define Ctrl_V_6                0x21FC
#define Ctrl_V_7                0x22FC
#define Ctrl_V_8                0x23FC
#define Ctrl_V_9                0x24FC

#define Ctrl_X_A                0x01FD
#define Ctrl_X_B                0x02FD
#define Ctrl_X_C                0x03FD
#define Ctrl_X_D                0x04FD
#define Ctrl_X_E                0x05FD
#define Ctrl_X_F                0x06FD
#define Ctrl_X_G                0x07FD
#define Ctrl_X_H                0x08FD
#define Ctrl_X_I                0x09FD
#define Ctrl_X_J                0x0AFD
#define Ctrl_X_K                0x0BFD
#define Ctrl_X_L                0x0CFD
#define Ctrl_X_M                0x0DFD
#define Ctrl_X_N                0x0EFD
#define Ctrl_X_O                0x0FFD
#define Ctrl_X_P                0x10FD
#define Ctrl_X_Q                0x11FD
#define Ctrl_X_R                0x12FD
#define Ctrl_X_S                0x13FD
#define Ctrl_X_T                0x14FD
#define Ctrl_X_U                0x15FD
#define Ctrl_X_V                0x16FD
#define Ctrl_X_W                0x17FD
#define Ctrl_X_X                0x18FD
#define Ctrl_X_Y                0x19FD
#define Ctrl_X_Z                0x1AFD
#define Ctrl_X_0                0x1BFD
#define Ctrl_X_1                0x1CFD
#define Ctrl_X_2                0x1DFD
#define Ctrl_X_3                0x1EFD
#define Ctrl_X_4                0x1FFD
#define Ctrl_X_5                0x20FD
#define Ctrl_X_6                0x21FD
#define Ctrl_X_7                0x22FD
#define Ctrl_X_8                0x23FD
#define Ctrl_X_9                0x24FD

#define Ctrl_Y_A                0x01FE
#define Ctrl_Y_B                0x02FE
#define Ctrl_Y_C                0x03FE
#define Ctrl_Y_D                0x04FE
#define Ctrl_Y_E                0x05FE
#define Ctrl_Y_F                0x06FE
#define Ctrl_Y_G                0x07FE
#define Ctrl_Y_H                0x08FE
#define Ctrl_Y_I                0x09FE
#define Ctrl_Y_J                0x0AFE
#define Ctrl_Y_K                0x0BFE
#define Ctrl_Y_L                0x0CFE
#define Ctrl_Y_M                0x0DFE
#define Ctrl_Y_N                0x0EFE
#define Ctrl_Y_O                0x0FFE
#define Ctrl_Y_P                0x10FE
#define Ctrl_Y_Q                0x11FE
#define Ctrl_Y_R                0x12FE
#define Ctrl_Y_S                0x13FE
#define Ctrl_Y_T                0x14FE
#define Ctrl_Y_U                0x15FE
#define Ctrl_Y_V                0x16FE
#define Ctrl_Y_W                0x17FE
#define Ctrl_Y_X                0x18FE
#define Ctrl_Y_Y                0x19FE
#define Ctrl_Y_Z                0x1AFE
#define Ctrl_Y_0                0x1BFE
#define Ctrl_Y_1                0x1CFE
#define Ctrl_Y_2                0x1DFE
#define Ctrl_Y_3                0x1EFE
#define Ctrl_Y_4                0x1FFE
#define Ctrl_Y_5                0x20FE
#define Ctrl_Y_6                0x21FE
#define Ctrl_Y_7                0x22FE
#define Ctrl_Y_8                0x23FE
#define Ctrl_Y_9                0x24FE

#define Ctrl_Z_A                0x01FF
#define Ctrl_Z_B                0x02FF
#define Ctrl_Z_C                0x03FF
#define Ctrl_Z_D                0x04FF
#define Ctrl_Z_E                0x05FF
#define Ctrl_Z_F                0x06FF
#define Ctrl_Z_G                0x07FF
#define Ctrl_Z_H                0x08FF
#define Ctrl_Z_I                0x09FF
#define Ctrl_Z_J                0x0AFF
#define Ctrl_Z_K                0x0BFF
#define Ctrl_Z_L                0x0CFF
#define Ctrl_Z_M                0x0DFF
#define Ctrl_Z_N                0x0EFF
#define Ctrl_Z_O                0x0FFF
#define Ctrl_Z_P                0x10FF
#define Ctrl_Z_Q                0x11FF
#define Ctrl_Z_R                0x12FF
#define Ctrl_Z_S                0x13FF
#define Ctrl_Z_T                0x14FF
#define Ctrl_Z_U                0x15FF
#define Ctrl_Z_V                0x16FF
#define Ctrl_Z_W                0x17FF
#define Ctrl_Z_X                0x18FF
#define Ctrl_Z_Y                0x19FF
#define Ctrl_Z_Z                0x1AFF
#define Ctrl_Z_0                0x1BFF
#define Ctrl_Z_1                0x1CFF
#define Ctrl_Z_2                0x1DFF
#define Ctrl_Z_3                0x1EFF
#define Ctrl_Z_4                0x1FFF
#define Ctrl_Z_5                0x20FF
#define Ctrl_Z_6                0x21FF
#define Ctrl_Z_7                0x22FF
#define Ctrl_Z_8                0x23FF
#define Ctrl_Z_9                0x24FF


#endif
